test_that("removes unwanted characters", {
  expect_equal(clean_name("ab`c"), "abc")
  expect_equal(clean_name("ab~c"), "abc")
  expect_equal(clean_name("ab!c"), "abc")
  expect_equal(clean_name("ab@c"), "abc")
  expect_equal(clean_name("ab#c"), "abc")
  expect_equal(clean_name("ab$c"), "abc")
  expect_equal(clean_name("ab%c"), "abc")
  expect_equal(clean_name("ab^c"), "abc")
  expect_equal(clean_name("ab&c"), "abc")
  expect_equal(clean_name("ab_c"), "abc")
  expect_equal(clean_name("ab=c"), "abc")
  expect_equal(clean_name("ab+c"), "abc")
  expect_equal(clean_name("ab[c"), "abc")
  expect_equal(clean_name("ab]c"), "abc")
  expect_equal(clean_name("ab{c"), "abc")
  expect_equal(clean_name("ab}c"), "abc")
  expect_equal(clean_name("ab|c"), "abc")
  expect_equal(clean_name("ab/c"), "abc")
  expect_equal(clean_name("ab\\c"), "abc")
  expect_equal(clean_name("ab?c"), "abc")
  expect_equal(clean_name("ab.c"), "abc")
  expect_equal(clean_name("ab<c"), "abc")
  expect_equal(clean_name("ab>c"), "abc")
  expect_equal(clean_name("ab,c"), "abc")
  expect_equal(clean_name("ab?c"), "abc")
})

expect_error(clean_name(1))
